### ISSUE TITLE
以后会有在线分享舰队配置的功能吗？

### ISSUE THREAD

**Issue by MinamiChan** [Diablohu/WhoCallsTheFleet#15]
活动的时候能看大佬的配置真心很有用。
还有就是海域敌方配置和制空值之类的信息也可以考虑再开一页收录一下。

**Comment by Diablohu** [comment]
现在正在开发相关功能，这也是在线版“舰队”功能迟迟没有移植完毕的原因

**Comment by Diablohu** [comment]
http://fleet.diablohu.com

Web版已实装该功能
