### ISSUE TITLE
舰队名输入反向 & 不能编辑改修等级 (Firefox  41.0 / linux) 

### ISSUE THREAD

**Issue by Javran** [Diablohu/WhoCallsTheFleet#16]
见图,输入内容实际是"test",但是字符是 `t` -> `et` -> `set` -> `tset` 这样变化的.

![2015-11-19_130642_3360x1080_scrot](https://cloud.githubusercontent.com/assets/1096354/11279435/a47b5678-8ebe-11e5-9dd3-e78bf17d9c59.png)

此外还有个问题是改修的装备等级无法修改,似乎不管怎么点击装备格中的输入框都得不到焦点.
![2015-11-19_131513_3360x1080_scrot](https://cloud.githubusercontent.com/assets/1096354/11279623/a3a8892c-8ebf-11e5-9e19-c75dcc8f0bc9.png)

(然而 google chrome 45 没有以上两个问题)

**Comment by Diablohu** [comment]
已记录
