### ISSUE TITLE
水母选不了司令部

### ISSUE THREAD

**Issue by mchome** [Diablohu/WhoCallsTheFleet#17]
rt，对了还有选择舰娘的时候，类别可以加个折叠按钮吗?

**Comment by Diablohu** [comment]
已记录，多谢提议

以及我想了解下，舰队配置选舰娘时，那个对比功能你觉得有必要么

**Comment by mchome** [comment]
比对功能我很少用，我一般是体感选船hhh

**Comment by Diablohu** [comment]
水母已可选司令部

**Comment by Diablohu** [comment]
该功能已在Web版实装，客户端版本也将在下次更新中实装该功能
欢迎使用
