### ISSUE TITLE
WEB版艦隊文件保存疑問

### ISSUE THREAD

**Issue by harukaxxxx** [Diablohu/WhoCallsTheFleet#18]
是誰呼叫艦隊在WEB上的實現著實是非常棒的消息！
簡單測試發現使用無痕視窗之類的方式就會讀不到已經儲存的艦隊
想請教WEB版的資料儲存實現方法是用餅乾還是伺服器端？

另WEB版若是使用伺服器端儲存艦隊資料
是否能夠有專屬頁面之類的服務可以分享配置？例：
http://fleet.diablohu.com/fleets/harukaxxxx

**Comment by Diablohu** [comment]
目前是本地存储，所以无痕浏览就无法存储了
未来的开发计划中有在线存储功能，不过以目前我个人的开发能力，这个功能要实现起来还有些遥远……

另外，在配置舰队后，当前页面URL就是直接访问**当前**配置的地址

**Comment by harukaxxxx** [comment]
了解:P
在線儲存功能的困難點是在於會員機制等等嗎？
如果不方便自己架設會員或許也可以考慮連結各大社群網站來實現
若困難點是在於PHP的話也可以用JSON之類的替代方案或許也行？

另外艦隊的配置網址在分享的部分若是能實現短網址的話也許會更加的方便呢！

**Comment by Diablohu** [comment]
不，只是简单的我不怎么懂服务器开发而已……

**Comment by harukaxxxx** [comment]
如果服務器有支援php的話其實很簡單的方法就是呼叫服務器改寫使用者資料.json來達到目的，但只能用先搶先贏的註冊方式（極簡）或社群網站連動管理。

**Comment by Diablohu** [comment]
现在是直接用GitHub Pages做服务器，纯静态
