### ISSUE TITLE
Web版选取舰娘对比时的错误

### ISSUE THREAD

**Issue by smarthsu** [Diablohu/WhoCallsTheFleet#19]
默认勾选“仅显示同种同名舰最终版本”时，选择有多个改造版本的舰娘某个中间形态（如·俾斯麦改），开始对比后不会显示该中间型态

![wctf-bug](https://cloud.githubusercontent.com/assets/14250548/11505196/29ebab54-9884-11e5-8706-7249b72c0a80.png)

Win8.1 & Chrome 46.0.2490.86 m

**Comment by Diablohu** [comment]
已记录，多谢提出

**Comment by smarthsu** [comment]
辛苦了，作为懒得记数据的人，对比功能的帮助很大
