### ISSUE TITLE
可不可以加一个类似“记事本”的文本功能？

### ISSUE THREAD

**Issue by jrdzm1993** [Diablohu/WhoCallsTheFleet#25]
这款软件真的很好用，无论是制空计算还是记一些阵容都很好用。十分感谢开发者的智慧与付出。还希望可以加一个类似“记事本”的文本功能，方便记录游戏里一些比较重要的东西，比如结婚啦，出货了等等。

**Comment by Diablohu** [comment]
我向你推荐——OneNote

**Comment by ibicdlcod** [comment]
233
