### ISSUE TITLE
OS X 10.10.3, nwjs-v0.12.2-osx-x64 无法启动 whocallsthefleet

### ISSUE THREAD

**Issue by Lencerf** [Diablohu/WhoCallsTheFleet#3]
whocallsthefleet 5月28日版本
启动提示 "Uncaught Error: ENOENT: no such file or directory, open '/Users/username/Library/Application Support/Who Calls the Fleet/Extracted Data/app/page/ships.html'", source: fs.js (515)

**Comment by Diablohu** [comment]
你的登陆用户名就叫 username 么……

**Comment by Lenserf** [comment]
@Diablohu 不是的，是真名拼音，不想泄露，故此处用 username 代替了
