### ISSUE TITLE
能不能自己设定背景图

### ISSUE THREAD

**Issue by mesiade** [Diablohu/WhoCallsTheFleet#4]
希望能够选择自己的图片作为背景图。

然后感觉切换内容的时候，是会先看到背景，再把东西载出来，会闪一下怪难受的。

顶上那个TAB可以放到左边来，这样更符合Mac的交互逻辑，不过考虑到需要跨平台的原因，可能要改的话windows那边也改了，所以不改问题也不大。

总体完成度还是非常高，很漂亮

**Comment by Diablohu** [comment]
已记录，多谢提出

**Comment by Diablohu** [comment]
Web版已更新，客户端版本将在下次更新时实装该功能
