### ISSUE TITLE
发现个舰娘错误，望修正

### ISSUE THREAD

**Issue by sherrymix** [Diablohu/WhoCallsTheFleet#41]
衣阿华改的赠送装备为4件，少了OS2U飞机，装备的飞机中有OS2U，其初始装备于某舰娘也是空的

**Comment by Diablohu** [comment]
commit https://github.com/Diablohu/WhoCallsTheFleet/commit/58b530d522acc65ecfcdaa6a5fe4876aa297cc71 已修正该问题
