### ISSUE TITLE
胧立绘缺少

### ISSUE THREAD

**Issue by DavidEuro** [Diablohu/WhoCallsTheFleet#50]
[虽然是不起眼的细节。。游戏中在近代化改修界面对胧(改限定？)进行改修，其立绘与之前几张夏季立绘都略有不同——立绘为胧吮吸饮料的样子。]
![qq 20160901010804](https://cloud.githubusercontent.com/assets/15035994/18136723/a88e8d3a-6fe0-11e6-94fd-b7bff01e78a0.png)

**Comment by Diablohu** [comment]
又偷偷摸摸改了？（这画师真是真爱……
