### ISSUE TITLE
零式艦戦62型(爆戦) 改修二舰

### ISSUE THREAD

**Issue by KagamiChan** [Diablohu/WhoCallsTheFleet#52]
![image](https://cloud.githubusercontent.com/assets/3816900/19573076/49512930-9737-11e6-82dc-0bfbfc60c30c.png)

根据多个 wiki 的资料（例如 [wikiwiki](http://wikiwiki.jp/kancolle/?%B2%FE%BD%A4%B9%A9%BE%B3#Bomber)），周日与周一的二舰中，瑞鹤改二应该是翔鹤改二的笔误？

**Comment by Diablohu** [comment]
多谢提出……
