### ISSUE TITLE
关于改修数据的一些差异

### ISSUE THREAD

**Issue by KagamiChan** [Diablohu/WhoCallsTheFleet#53]
你好，我是 poi 改修插件的维护者之一，首先感谢允许我们使用是谁呼叫舰队的改修数据。

最近有机会比较详尽对比了是谁呼叫舰队的改修数据和 wikiwiki 数据的不同，然后发现一些差异，在这边提一下，作为参考。因为我也没有做过验证，下边的说法的“应”是以 wikiwiki 数据为基准的，并不意味着真实的数据情况

+ id = 63 12.7cm連装砲B型改二 第二阶段的确保开发资材应为 3
+ id = 133 381mm/50 三連装砲 升级阶段的确保开发资材应为 22
+ id = 39 25mm連装機銃 缺少鬼怒改二
+ id = 49 25mm単装機銃，皋月周二应不可改修

**Comment by Diablohu** [comment]
这两天我再根据几个数据源重新比对一下，多谢提出
