### ISSUE TITLE
兼容艦載機厨v4格式导入

### ISSUE THREAD

**Issue by Javran** [Diablohu/WhoCallsTheFleet#56]
详见 http://kancolle-calc.net/deckbuilder.html 格式说明.

新版的区别是, `version: 4`, 以及区分改修星数`rf`和舰载机熟练度`mas`

**Comment by Diablohu** [comment]
现在不是已经兼容了么……

**Comment by Javran** [comment]
@Diablohu 舰载机的改修星数没有导入,比如这段:

`{"version":4,"f1":{"s1":{"id":185,"lv":128,"luck":26,"items":{"i1":{"id":152,"rf":10,"mas":7},"ix":{"id":72}}}}}`
