### ISSUE TITLE
关于装备【彩云（运输用拆卸版）】的可装备舰种

### ISSUE THREAD

**Issue by Johnjolno** [Diablohu/WhoCallsTheFleet#58]
可以装备该装备的，航空战列舰(BBV)、航空巡洋舰(CAV)，没有标示在『可装备于的舰种』里。

**Comment by Diablohu** [comment]
fixed in https://github.com/Diablohu/WhoCallsTheFleet/commit/ee3989171d473130b51c2d5a75d7ebb825c80043
