### ISSUE TITLE
从舰载机厨导入代码失败

### ISSUE THREAD

**Issue by finalfirexs** [Diablohu/WhoCallsTheFleet#6]
我的链接http://www.kancolle-calc.net/deckbuilder.html?id=6eKuFhYlg7
从这里复制代码导入【是谁呼叫舰队】得到的是一个空空的配置列表

**Comment by Diablohu** [comment]
最新版本（0.7.9）无此问题……

**Comment by finalfirexs** [comment]
OK, 问题解决
