### ISSUE TITLE
Akashi upgrade arsenal Ro.44 

### ISSUE THREAD

**Issue by DynamicSTOP** [Diablohu/WhoCallsTheFleet#61]
Hi!
I would like to request an upgrade for Ro.44
https://github.com/Diablohu/WhoCallsTheFleet/blob/master/app-db/items.json#L151

based on http://akashi-list.me/#w215 for 6~9
`[14,18,6,7,164,1]`

**Comment by Diablohu** [comment]
thanks for support. sorry for the late update.

app and website will update soon
