### ISSUE TITLE
关于最速舰bug

### ISSUE THREAD

**Issue by GoLoCom** [Diablohu/WhoCallsTheFleet#62]
不管只要随便放个改良锅高速就会变成最速船了
低速船也会变高速+

**Comment by Diablohu** [comment]
似乎只有部分船有这个问题，可否说明下你遇到这个问题的舰娘？

**Comment by GoLoCom** [comment]
好像不需要反馈了Σ( ° △ °|||)︴

**Comment by GoLoCom** [comment]
伊13,14没改过来
![temp2](https://cloud.githubusercontent.com/assets/25927990/24764997/c7108ea4-1b28-11e7-9a68-08e3f5946bb3.png)
![temp1](https://cloud.githubusercontent.com/assets/25927990/24764988/bffe2432-1b28-11e7-8ddd-c6585ccc9400.png)

**Comment by Diablohu** [comment]
多谢提出

目前的代码里，是按照舰级手动指定的，像这中新的舰级当时就没改……
