### ISSUE TITLE
“舰队”标签中对于配置的潜水舰娘的夜战攻击方式以及攻击力计算不准确？

### ISSUE THREAD

**Issue by CopsiTG** [Diablohu/WhoCallsTheFleet#67]
偶然在wiki上看到潜水舰娘在装备后期型鱼雷、潜艇用电探的时候夜战CI拥有特殊的倍率，分别是1.6×2以及1.75×2，目前0.20.9版本中计算时好像依然将潜水舰娘按照水面舰一并计算（鱼雷CI1.5×2），鱼雷+潜艇用电探的特殊CI则没有被考虑在内，显示为通常。

**Comment by Diablohu** [comment]
多谢提出
另外可否提供一下这个wiki页面？

**Comment by CopsiTG** [comment]
夜間特殊攻撃(夜戦・攻撃分類) 列：
http://wikiwiki.jp/kancolle/?%C0%EF%C6%AE%A4%CB%A4%C4%A4%A4%A4%C6#NightBattle

**Comment by Diablohu** [comment]
fix in https://github.com/Diablohu/WhoCallsTheFleet/commit/0f1f561520bfc8325dcf73eba3b4eeca33170cbe
