### ISSUE TITLE
希望能明确一下舰娘属性页的射程以免造成误解

### ISSUE THREAD

**Issue by NankyokuDenka** [Diablohu/WhoCallsTheFleet#72]
因为炮的射程和舰娘的射程不同，可能会造成误解。

比如aww的射程为短，显示也是短，因为初始装备都是短射程，这没有误解。
但是sara和zara因为初始装备有长射程炮，现在显示的属性也是射程长，但是据我所知只有zara改二才是长，这就会造成误解。
还有罗马和意大利也是这样。

**Comment by Diablohu** [comment]
@NankyokuDenka 我很确定你错了…… 🤣
![2017-07-29 19-33-25 16](https://user-images.githubusercontent.com/1946774/28744502-d0b5fd52-7494-11e7-9ba5-e2e635016be1.png)
![2017-07-29 19-33-59 73](https://user-images.githubusercontent.com/1946774/28744505-f4e82b14-7494-11e7-899b-f85401bccb6a.png)

事实上舰娘射程这个数据是直接从客户端里抽的，全程没有人工干预……

**Comment by NankyokuDenka** [comment]
好吧。这真是好消息，我被某些人误导了(ˉ▽ˉ；)...
