### ISSUE TITLE
部分新装备类型错误

### ISSUE THREAD

**Issue by DavidDiao** [Diablohu/WhoCallsTheFleet#73]
Spitfire*的类型是陆军战斗机而不是舰载战斗机，以及Spitfire Mk.IX(熟练)是喷火不是海喷火

**Comment by Diablohu** [comment]
fixed in https://github.com/Diablohu/WhoCallsTheFleet/commit/3ea1d567b207e17f8576b991e413659e1291fc4a

**Comment by DavidDiao** [comment]
前面说的Spitfire*说的是所有Spitfire开头的啊(╯‵□′)╯︵┻━┻Spitfire Mk.I、Spitfire Mk.V也都是陆战啊(╯‵□′)╯︵┻━┻

**Comment by Diablohu** [comment]
![image](https://user-images.githubusercontent.com/1946774/29256629-5bbcfd7e-80de-11e7-9b4d-8ac4648b9fb4.png)
hello? (￣_,￣ )

**Comment by DavidDiao** [comment]
那条评论是在0.22.1更新前3小时发的恩
